### PR TITLE
Changing api so that users just specify server to forward i2p traffic to.

### PR DESCRIPTION
**Pull request by mooseman1241**
This makes it easier for users to adapt existing servers to use solitude. There is a helper struct for de-serializing and serializing messages.

### CODE REVIEW

**Comment by mooseman1241** [comment]
Will make examples work next

**Comment by linden** [comment]
Currently the messages are never received on my machine, does it work for you?
We should add that to the tests.

Looks like a major improvement (good call), after that's fixed I'll work on the merge conflicts.

**Comment by mooseman1241** [comment]
I have local changes that I haven't pushed yet. With those changes it works, there are still something's I needed to iron out before pushing though

**Comment by mooseman1241** [comment]
I'll also add that currently, deserializing messages doesn't work, however the server does receive the messages

**Pull request merged**
