### PR TITLE
feat!: Add RAW & Stream `Session` styles

### PR DESCRIPTION
**Pull request by mooseman1241**
Will use an enum to allow the user to choose which session style to use, datagram, raw, or stream.

### CODE REVIEW

**Comment by mooseman1241** [comment]
#8

**Comment by mooseman1241** [comment]
#1 Issue

**Comment by mooseman1241** [comment]
Currently needs a helper struct for Stream and Raw messages, tests, and examples

**Comment by mooseman1241** [comment]
Having trouble trying to figure out #10

**Comment by linden** [comment]
instead of `new(service: String, session_style: SessionStyle)` and `forward(&mut self, forwarding_address: &str, port: u16)`,
I think a single call to `new(&mut self, session_style: SessionStyle, forwarding_address: &str, port: u16)` makes more sense considering in all use cases you'll need to call both.

**Comment by mooseman1241** [comment]
You don't in all cases. As a stream client you call connect_stream instead of forward.

**Comment by linden** [comment]
Oh, I didn't realize that, in that case it definitely seems like the right approach.

**Comment by linden** [comment]
Currently every test using the SAM UDP socket fail for me.

**Comment by mooseman1241** [comment]
Yes, it's not done yet

**Comment by linden** [comment]
🎉

**Pull request merged**
